# Generated by Django 4.2.9 on 2024-01-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoSemestr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/media/media/media/post_image'),
        ),
    ]
