# Generated by Django 4.2.9 on 2024-01-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoSemestr_app', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
