# Generated by Django 4.2.9 on 2024-01-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoSemestr_app', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='body',
        ),
    ]
